apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.backend.namespace | default "default"}}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.label }}
    spec:
      containers:
      - name: flask
        image: pardiuman/appres{{ if eq .Values.production "dev" }}-dev{{ end }}
        imagePullPolicy: {{ .Values.backend.imagepullpolicy }}
        resources:
          requests:
            cpu: 256m
            memory: 128Mi
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
        envFrom:
          - secretRef:
              name: {{ .Values.secret.name }}
        env:
          - name: MYSQL_HOST
            value: {{ .Values.db.service.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  selector:
    app: {{ .Values.backend.label }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    {{- if eq .Values.backend.service.type "NodePort" }}
    nodePort: {{ .Values.backend.service.nodePort }}
    {{- end }}
  type: {{ .Values.backend.service.type }}
