apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.label }}
    spec:
      containers:
        - name: {{ .Values.db.containerName | default "database" }}
          image: mysql
          ports:
          - containerPort: {{ .Values.db.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql/
            - name: mysql-create-table
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
        - name: mysql-create-table
          configMap:
            name: {{ .Values.cm.name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
spec:
  selector:
    app: {{ .Values.db.label }}
  ports:
  - port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.targetPort }}
